In [1]:
a=[1,2,3,4,5]


In [3]:
print(a)

[1, 2, 3, 4, 5]


In [5]:
print(type(a))

<class 'list'>


In [7]:
np_a = np.array(a)

NameError: name 'np' is not defined

In [9]:
print(np_a)

NameError: name 'np_a' is not defined

In [11]:
L = range(1000)
%timeit [i**2 for i in L]

134 μs ± 2.85 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [13]:
a = np.arrange(1000)
%timeit a**2

NameError: name 'np' is not defined

In [15]:
a = np.array([0, 1, 2, 3])
a

NameError: name 'np' is not defined

In [17]:
a.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [29]:
a.shape

AttributeError: 'list' object has no attribute 'shape'

In [21]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [23]:
my_matrix = [[1,2,3], [4,5,6],97,8,9]]
my_matrix

SyntaxError: unmatched ']' (1705586829.py, line 1)

In [25]:
import numpy as np

In [27]:
np.zeros(3)

array([0., 0., 0.])

b = np.zeros((2,2))
b

In [33]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
d = np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [41]:
a = np.diag([7, 9, 3, 4])
a

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [43]:
np.diag(a)

array([7, 9, 3, 4])

In [47]:
random_array = np.random.randint(1,121,5)
print(random_array)

[90  2 28 67 49]


In [49]:
a = np.random.rand(4)
a

array([0.61812736, 0.03380568, 0.02640447, 0.30310139])

In [51]:
a = np.random.randn(100)
a

array([-1.93272763e+00,  1.85217758e+00,  3.64184807e-01, -6.68908751e-02,
        6.20413698e-01,  1.61844168e-01,  2.31178531e-01, -7.33942910e-01,
        9.05419778e-04,  1.55306236e-01, -1.50277492e-01, -1.18237012e+00,
       -1.51010130e-01, -7.13034322e-01,  9.19954089e-01, -9.88976684e-02,
       -1.09873849e+00,  8.12725431e-01, -7.58705606e-01,  1.00461883e+00,
        8.11859204e-01,  5.52347817e-01,  4.86633570e-01, -5.20600951e-01,
       -3.03100121e+00,  1.66305661e-01,  1.20190246e+00, -5.71250516e-01,
        7.13951366e-01, -3.02029160e-01,  5.90863624e-01, -1.31121716e+00,
       -1.73832961e-01, -5.55041764e-01,  2.54656627e+00,  1.82575562e-01,
        7.09843303e-02, -1.77383313e+00, -1.20830420e+00, -3.18815899e-01,
        9.73825811e-01,  7.07808445e-01, -1.68872235e+00,  1.37606672e+00,
        8.93766091e-01,  4.86581944e-01, -5.97902243e-01, -4.97566613e-01,
        1.44670545e-01,  1.54921874e+00, -9.40800336e-02,  7.07608088e-01,
        1.63643690e+00,  

In [55]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [57]:
arr = np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [59]:
a1=arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("shape of a: {}".format(a.shape))

[[1 2 3]
 [4 5 6]]
shape of a: (2, 3)


In [63]:
b = a.reshape(3,2)
print(b)
print("shape pf b: {}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
shape pf b: (3, 2)


In [65]:
a = np.array([[1,2,3],[4,5,6]])
print("shape: {}".format(b.shape))

shape: (3, 2)


In [69]:
a = np.array([[1,2,3],[4,5,6]])
pringt("shape: {}".format(b.shape))
print(a)

NameError: name 'pringt' is not defined

In [71]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [73]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [75]:
c.ravel()

array([1, 4, 2, 5, 3, 6])

In [79]:
a = np.array([[5, 4, 6], [2,8,2]])
b = np.sort(a, axis-1)
b

NameError: name 'axis' is not defined

In [83]:
a = np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [85]:
a = np.diag([1, 2, 3])
print(a)
print(a[2,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [87]:
a[2,1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [89]:
a = np.arrange(4,18)
a

AttributeError: module 'numpy' has no attribute 'arrange'

In [91]:
a[1:8:2]

array([[0, 2, 0]])

In [93]:
a = np.arrange(10)
a[5:]

AttributeError: module 'numpy' has no attribute 'arrange'

In [97]:
a[5:] = 10
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])